### ISSUE TITLE
Force reload

### ISSUE THREAD

**Issue by fcristel** [ncuillery/angular-breadcrumb#106]
How can I force a reload of the page when i click on a link from the breadcrumb?

Having for example "Products" and when clicking on one of them, then the breadcrumb gets "Products / Milk", with the possibility to click on "Products" part of the breadcrumb. But when you do so, there is no reloading; just opens from cache.

**Comment by jlmitch5** [comment]
@fcristel did you ever figure this out?

**Comment by jlmitch5** [comment]
I figured out a workaround.

For the parent parameter, you can use a function that has access to `$scope`.  You can thus do a `$scope.$emit`, and thus, you can handle that in your controller using a `$scope.$on` and then reload what you need.

**Comment by ncuillery** [comment]
A less tricky solution could be using the `reload` option of the [ui-sref-opts](http://angular-ui.github.io/ui-router/site/#/api/ui.router.state.directive:ui-sref) directive.

You can define a [custom template](https://github.com/ncuillery/angular-breadcrumb/wiki/Templating#custom-template) to use this directive in `ncyBreadcrumb`.
