### ISSUE TITLE
Question: Is there an option to display entire breadcrumb from root page

### ISSUE THREAD

**Issue by JustinLien** [ncuillery/angular-breadcrumb#111]
E.g.:

![image](https://cloud.githubusercontent.com/assets/688800/11136389/f3bbe114-8962-11e5-8e59-7605c654ec3e.png)

Starting at home the entire breadcrumb is grey out, will become clickable when moving to Sample.

**Comment by ncuillery** [comment]
I suppose it's possible (but ugly) by using an [inline custom template](https://github.com/ncuillery/angular-breadcrumb/wiki/Templating#custom-template).

You can configure the custom template in the same `.config` of your routes definition. Then, you have to include an array of your states in a `ngInit` and use it to render a string or a link.

I think I got something here:

http://plnkr.co/edit/7Zjy2ngIYX4U1GSnIfoT?p=preview
