### ISSUE TITLE
Add external url for the prefix state

### ISSUE THREAD

**Issue by praveenpenjarla** [ncuillery/angular-breadcrumb#117]

**Comment by praveenpenjarla** [comment]
Could you please let me how can we add the external url for the prefix state

**Comment by ncuillery** [comment]
Hi,

I suggest not using the prefix state and defining a [custom template](https://github.com/ncuillery/angular-breadcrumb/wiki/Templating#custom-template) where you can specify whatever you want at the beginning of the breadcrumb.
