### ISSUE TITLE
Translating angular breadcrumb last

### ISSUE THREAD

**Issue by 1nfinite** [ncuillery/angular-breadcrumb#125]
I understand that the ncy-breadcrumb can be translated using angular translate with custom template. However, I could not find a way to translate ncy-breadcrumb-last from the documentation.

`<span ncy-breadcrumb-last></span>`

**Comment by freethejazz** [comment]
@1nfinite: I'm working on a fix for #123, which will allow you to use a custom template for `ncy-breadcrumb-last`. You'll see in the comments there that I'm in a bit of a yak shave, but hope to surface soon and address the original issue.

**Comment by freethejazz** [comment]
@1nfinite I've got a PR open for creating a template for this, but I discovered an undocumented way of doing this when writing tests for the new functionality. You simply set a value to the ncyBreadcrumbLast directive and that value gets used for the template:

```<span ncy-breadcrumb-last="{{ncyBreadcrumbLabel | translate}}"></span>```
