### ISSUE TITLE
Extra '/' when using bootstrap 3.3.6 css

### ISSUE THREAD

**Issue by jdriesen** [ncuillery/angular-breadcrumb#132]
Hi Sir,
First of all, thanks for this GREAT tool !
I found a small issue... It seems that an extra '/' is generated when using the latest version of bootstrap.css....

You're using v2.3.2 of bootstrap.css
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/2.3.2/css/bootstrap.min.css">
  
When I change this to v3.3.6
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">

it seems that an extra '/' is generated.
![breadcrumb](https://cloud.githubusercontent.com/assets/1137648/13281265/10e27aa6-dae3-11e5-8fdb-1c97c2460e0d.png)

Any idea how this can be solved ?

Thanks in advance for your reply.
Johnny Driesen
Belgium

**Comment by jdriesen** [comment]
Problem solved...
My bad ... SORRY ...
Solution: just change 'bootstrap2' into 'bootstrap3' in the line below ...

.config(function($breadcrumbProvider) {
    $breadcrumbProvider.setOptions({
      prefixStateName: 'home',
      template: 'bootstrap2'
    });
  })

Once again ... sorry for my stupid question...
Johnny

**Comment by freethejazz** [comment]
:D glad you were able to resolve it on your own! Can you close the issue since you were able to resolve it in your code?

**Comment by ncuillery** [comment]
Hi guys,

Sorry I don't have time to maintain this repo as much as I would like.

Bootstrap 3 has just been released when I created this module, so I set the Bootstrap 2 template as default. But nowadays, Bootstrap 3 is widely used, so it must be the default.

 I suggest to leave this issue open to keep that in mind.

**Comment by freethejazz** [comment]
Hey @ncuillery, it looks like bootstrap3 is already the default: https://github.com/ncuillery/angular-breadcrumb/blob/master/src/angular-breadcrumb.js#L21

**Comment by ncuillery** [comment]
Oh my bad :smile:

**Comment by jdriesen** [comment]
Well, I picked up the code from a Plunkr somewhere somehow …, and that’s why I encountered that issue…

 

Grtz,

 

Johnny
