### ISSUE TITLE
Doesn't work with Angular 1.5.X

### ISSUE THREAD

**Issue by CSchulz** [ncuillery/angular-breadcrumb#160]
I have encountered the issue the directive isn't rendered properly (nothing is shown) with Angular 1.5.X. I have tried to debug it and no breakpoint is ever hit.

I have tried to update the bower.json to use a newer Angular version to run the tests against it without success.

I have changed in bower.json the version to **>= 1.5.0**, ran bower install and grunt, but it still uses the old versions:
```
Running "jshint:gruntfile" (jshint) task
>> 1 file lint free.

Running "jshint:sources" (jshint) task
>> 1 file lint free.

Running "jshint:test" (jshint) task
>> 28 files lint free.

Running "clean:test" (clean) task

Running "shell:testMinimal" (shell) task
bower angular#=1.2.29       not-cached https://github.com/angular/bower-angular.git#=1.2.29
bower angular#=1.2.29          resolve https://github.com/angular/bower-angular.git#=1.2.29
bower angular-mocks#=1.2.29 not-cached https://github.com/angular/bower-angular-mocks.git#=1.2.29
bower angular-mocks#=1.2.29    resolve https://github.com/angular/bower-angular-mocks.git#=1.2.29
bower angular-sanitize#=1.2.29       not-cached https://github.com/angular/bower-angular-sanitize.git#=1.2.29
bower angular-sanitize#=1.2.29          resolve https://github.com/angular/bower-angular-sanitize.git#=1.2.29
bower angular-ui-router#=0.2.18      not-cached https://github.com/angular-ui/angular-ui-router-bower.git#=0.2.18
bower angular-ui-router#=0.2.18         resolve https://github.com/angular-ui/angular-ui-router-bower.git#=0.2.18
```

**Comment by smajl** [comment]
Just to inform you. It *does WORK* with Angular 1.5.X without any problems. So looks like a problem with your implementation. Feel free to post your code in some code playground so we can see where you are making a mistake or close this issue.

**Comment by CSchulz** [comment]
You are right, it works with Angular 1.5.X. I don't know what was wrong, it works suddenly. There were no errors in the console.
