### ISSUE TITLE
moving all the logic into the service

### ISSUE THREAD

**Issue by mastilver** [ncuillery/angular-breadcrumb#25]
Hi

What I want to do is to simplify the code of the directive and put all the logic into the directive.
Advantages are:
* easier testing (for the directive, you just have to mock $breadcrumb)
* optimization (as the step are not destroyed and recreated several time during the rendering process)

Some work to do:
* manage the unregistration of the watcher
* update unit test

I have worked on top of #23 so as soon as you merge it I will rebase my branch with your master and submit a pull request.

My code: c9d8ae48646ff9a84db0e9fdfb1fe7d63c075d62

**Comment by ncuillery** [comment]
Still waiting for the PR :wink: 

The project has moved a lot since nearly one year. And the issue is maybe unnecessary now.

I closed the issue. Feel free to reopen and comment the actual master if you have time.

**Comment by mastilver** [comment]
Hi

Sorry for that, I started working on it but I parked it for a while and now my code is completely out-focus.

Carry on the good work, this project is awesome! ;)
