### ISSUE TITLE
Route Parameters Are Lost

### ISSUE THREAD

**Issue by elalchemist** [ncuillery/angular-breadcrumb#26]
Hello,

Excellent plugin!

However, I cannot use the breadcrumb with routes that have parameters. When I click on a breadcrumb the route has no parameter in it. For example, what was before 'app/levels/1' simply becomes 'app/levels/'. How do I get the breadcrumb to keep the route parameters?

**Comment by vchandrol** [comment]
Hi @ncuillery 
  if we have search box and if we enter some text and that folder/file exist in ui route than how can we show search path in breadcrumb...could you please provide solution for this.
