### ISSUE TITLE
ncyBreadcrumbLabel {{Substitution}} value lost after refresh

### ISSUE THREAD

**Issue by MBing** [ncuillery/angular-breadcrumb#31]
First of all, thanks a lot for this great plugin!!

I am using this with dynamic values and I encountered a possible issue. This might regard to #15 But I am not sure..

**How it works now** 
I give the label a dynamic value, similar like the example below. When I go to a certain state (e.g. `ui-sref='mystate'`) this is working and it shows the dynamic value it got from the controller as supposed to.
```php
.state('mystate', {
  url: '/url',
  views: {
    "@": {
      templateUrl: 'tpl.html',
      controller: function  ( $scope,   $state,   $stateParams ) {
         $scope.title = 'mytitle';
      }
    }
  },
  data: { 
    ncyBreadcrumbLabel: '{{title}}'  
  }
 });
```

**Problem** 
When I refresh the page or go to a direct url (e.g. `somesite.com/url`) to get the state. The dynamic value isn't passed to the breadcrumb label. It seems like it is only working when you are using the states via `ui-sref` or maybe others as well.. The value is still in the scope, but somehow the breadcrumb can't get to it and the value it once had is lost.

**Possible solution** 
Make sure that the dynamic value is saved somewhere or it can get to the scope where the value was in so you can still use it and when you go to a state and there is a value available (e.g. _!empty String_) which is changed, then it should update the current value. As the states change, the scope also changes and it's possible that's the reason why it is looking in the current scope for the value. Using the $rootScope of Angular and an array of values which check with the current state where it is now. I will try to implement an example with the usage of $rootScope in the meanwhile.

**Comment by ncuillery** [comment]
I hope I answered to your interrogation.

I close the issue. The angular-translate question is tracked [here](https://github.com/ncuillery/angular-breadcrumb/issues/65).
