### ISSUE TITLE
bindings don't seem to work

### ISSUE THREAD

**Issue by paulflo150** [ncuillery/angular-breadcrumb#33]
Hi guys,
sorry for creating an issue if this turns out not to be one. 

I have a project in which I load everything via requirejs, and I am not able to get the bindings to work (perhaps I am using it the wrong way).

Here is a stripped down version of the project, both views display the breadcrumbs, but they do not seem to see the scope of either controller.

https://github.com/paulflo150/breadcrumbs1

Any thoughts?

Thanks,
Paul

**Comment by ncuillery** [comment]
Closed after 6 months of inactivity.

Feel free to reopen if your problem is still current.
