### ISSUE TITLE
Integrate with ngAnimate

### ISSUE THREAD

**Issue by seaneagan** [ncuillery/angular-breadcrumb#40]
The animation could probably have 2 steps:

* remove all breadcrumbs up to the longest matching substate of the new state
* add the rest of the crumbs for the new state.

**Comment by ncuillery** [comment]
It goes well with a custom template using the directive [ngAnimateSwap](https://docs.angularjs.org/api/ngAnimate/directive/ngAnimateSwap) :smiley: 

http://plnkr.co/edit/rApuGDO3tB7zOJ1oSpAT?p=preview

Let's keep this plunker as reference for further issues / questions about ngAnimate.

**Comment by ptitdje45** [comment]
i tried your answer @ncuillery but i got a [$compile:tplrt] Template for directive 'ncyBreadcrumb' must have exactly one root element. breadcrumb.tmpl.html. 

Did i miss something ?
