### ISSUE TITLE
famous-angular breaks angular-breadcrumb

### ISSUE THREAD

**Issue by krikkiteer** [ncuillery/angular-breadcrumb#58]
Hi there - first of all thanks for the great tool! :+1: 

But - there seems to be a conflict with famous-angular.. when both are used angular-breadcrumb stops working.. i can't really figure out why, but i created a plnkr to demonstrate.. 

the error occurs, after navigating to the second view.. and then consistently.. i have no idea why ;)
maybe you have an idea ?

http://plnkr.co/edit/wClm2JUizgtSTpkgawvt

i'd be glad for any feedback!

**Comment by ncuillery** [comment]
Hi, sorry for the one-year delay :hushed: .

Is the problem still here ? I know nothing about famous-angular, is it still in use ? (the [README.md](https://github.com/Famous/famous-angular) starts with "This integration library is no longer supported by Famo.us"...

The plunker is no longer working.

I close this issue and the associated PR. Feel free to reopen you still need a fix.
