### ISSUE TITLE
bread crumb link goes to wrong url

### ISSUE THREAD

**Issue by ansorensen** [ncuillery/angular-breadcrumb#64]
I'm using angular-breadcrumb with ui state router.  I have anchor with ui-sref="app.page", which becomes href="/page", and it works perfectly, taking me to http://localhost/app/#/page.  However, the breadcrumb for app.page only has href="/page", and it takes me to http://localhost/page, which 404s.

my state provider is

```
$stateProvider
  .('root', {
    'abstract': true,
    'views': {...}
  })
  .('app', {
    'abstract': true,
    parent: 'root',
    'views': {...},
    ncyBreadcrumb: {
      skip: true
   }
.('app.home', {
    url: '/',
    views: {...}
    ncyBreadcrumb: {
      label: 'Home'.
      parent: 'app'
    }
})
.('app.page', {
    url: '/page',
    views: {...}
    ncyBreadcrumb: {
      label: 'Page'.
      parent: 'app'
    }
})
.('child', {
    url: '/page/:childId',
    views: {...}
    ncyBreadcrumb: {
      label: '{{child.name}}'.
      parent: 'app.page'
    }
})
```

When I'm on the child page, and click the breadcrumb for app.page (which has the same href as the main nav), I end up at the wrong URL.  It looks like what UI Router takes as '/' is the root of the angular app ('http:/localhost/app/#/') but whereas breadcrumb interprets '/' as 'http:/localhost'.  The latter is not even in my app.

**Comment by jksenthilraja** [comment]
I  updated my UI-router to 0.2.13 and my issue was resolved.
