### ISSUE TITLE
API Page / Documentation Missing and/or Inaccurate

### ISSUE THREAD

**Issue by jancel** [ncuillery/angular-breadcrumb#66]
On this page: https://github.com/ncuillery/angular-breadcrumb/wiki/API-Reference

This documentation states one thing, and it just doesn't look like compilable javascript. I added it to my code and it doesn't work. I've tried the documented way as well as similar (non-syntax erroring) ways to handle this to no avail.  Any help on how to actually write this out would be great.

There is a statement: Both declarations (string or function) accept url params. The syntax is the same as the UI-router uiSref directive :

```
$stateProvider.state('product.detail', {
  url: '/{productId}',
  views: [...],
  ncyBreadcrumb: {
    parent: 'category.list({cat: 'product'})'
  }
})
```

**Comment by ncuillery** [comment]
Maybe you are disturbed by the `[...]`: Of course it's not compilable javascript, it's an [ellipsis](http://en.wikipedia.org/wiki/Ellipsis) for the views definition.

You must include the real views definition here (or a couple controller / view). See the [UI-Router doc](https://github.com/angular-ui/ui-router/wiki) for details.

**Comment by jancel** [comment]
Okay. I guess you caught me not being specific enough. I'm actually talking about the specific line:

```
parent: 'category.list({cat: 'product'})'
```

I'm not disturbed at all. I like your library, but the documentation is off. And personally, the views has nothing to do with ncyBreadcrumb at all, unless I'm mistaken.

**Comment by ncuillery** [comment]
My bad !

I didn't see the mistake with the single quote.

I fix it,

Thanks
