### ISSUE TITLE
Add option for abstract states to be included

### ISSUE THREAD

**Issue by epelc** [ncuillery/angular-breadcrumb#69]
You should be able to include a single abstract state without having to set the global `includeAbstract` bool to true. Ideally if `skip` was set to false on an abstract state it should just work. Right now the only way to include just a single abstract state is to enable the global flag then set `skip:true` on all your other abstract states.

**Comment by ncuillery** [comment]
If I understand well, you propose to make the `includeAbstract` a state-level option instead of a global one. Am I right ?

It makes sense but it will introduce a breaking change :-/

**Comment by epelc** [comment]
@ncuillery I think we should add an override for the global `includeAbstract` to states. So if the global one is set to false each state can override it and set it to true.

I'm pretty sure it can be done without breaking things. But it might be more elegant if you could detect `skip:false` on abstract states instead.

**Comment by ncuillery** [comment]
I close this issue in favor of a good PR here: #78 

It covers your needs. Feel free to reopen if I'm wrong.
