### ISSUE TITLE
ncybreadcrumbLink losing the # when building the link

### ISSUE THREAD

**Issue by keertijoshi** [ncuillery/angular-breadcrumb#70]
I have the latest version of angular, angular ui-router and angular breadcrumb. When i use it on my localhost with port 3000 or 8000 it works fine, however when I test it on an ip like 172.16.142.1 (port 443), the ncybreadcrumbLink loses the # (eg, ncyBreadcrumbLink: "/hyperfilerView/storageClassesView") when it should have been ncyBreadcrumbLink: "#/hyperfilerView/storageClassesView"

I am having this issue after the angular and angular breadcrumb upgrade.

**Comment by ncuillery** [comment]
Hi, sorry for the late answer. I lack time.

The values of hrefs are directly generated from the method `$state.href()`, the same used by the `ui-sref` directive. Please can you try to generate a link with the ui-router's `ui-sref` directive (totally outside of the breadcrumb) and tell me if it's working ?

Which versions of angular / ui-router / angular-breadcrumb do you use ?

**Comment by alFReD-NSH** [comment]
I had this issue, but resolved, when I upgraded my ui-router.

**Comment by ncuillery** [comment]
Closed after 6 months of inactivity
