### ISSUE TITLE
Label does not work on multi- and nested views

### ISSUE THREAD

**Issue by hanssulo** [ncuillery/angular-breadcrumb#75]
Working with multi- and nested views, turns out breadcrumb fails to display the nested view's label. Despite that, url is correctly parsed.

        .state('booking', {
            url: '/booking',
            views : {
                '' : {
                    templateUrl : 'booking/booking.html'
                },
                        'sidebar@booking' : {
                            templateUrl : 'booking/sidebar.html',
                            controller : 'SideBarCtrl'
                        },
                                'content@booking' : {
                                    templateUrl : 'booking/content.html',
                                    controller : 'ContentCtrl'
                                }
            },
            ncyBreadcrumb : {
                label : 'Bookings'
            }
        })
        .state('booking.all', {
            url : '/all',
            ncyBreadcrumb : {
                label : 'Total Bookings'
            }
        });

Expecting Home / Bookings / Total Bookings
-> Got Home / Bookings

Url is correct never the less, .../booking/all

Edit: FIXED as following

        .state('booking.all', {
            url : '/all',
            mainView : 'content',
            ncyBreadcrumb : {
                label : 'Total Bookings'
            },
            views : {
                'content@booking' : {
                    template : 'test'
                }
            }
        });

**Comment by hanssulo** [comment]
Seen the mainView workaround, works. Thanks

**Comment by ncuillery** [comment]
Don't thank me, it's not ready yet :)

Close as dup of #62
