### ISSUE TITLE
ng-include of svg not woring

### ISSUE THREAD

**Issue by bodagetta** [ncuillery/angular-breadcrumb#87]
I'm able to use SVGs in labels like this

    .state('statename', {
        url; '/myurl',
        ncyBreadcrumb: {
            label: '<img src="/assets/icon.svg' />{{labelText}}'
        }
    })

and all looks well, but I want to be able to style the SVGs, so I need to include them inline.

When I try to use them inline, like this

    .state('statename', {
        url; '/myurl',
        ncyBreadcrumb: {
            label: '<span ng-include="/assets/icon.svg"></span>{{labelText}}'
        }
    })

it doesn't render the SVG.

**Comment by ncuillery** [comment]
This syntax `<span ng-include="/assets/icon.svg"></span>` doesn't work, in the breadcrumb or not (plain angular template).

You can see it in [this plunker](http://plnkr.co/edit/eSOHqzJNPnICcRUZ4t98?p=preview).
You can see also a working example of SVG in a breadcrumb label (click on "Element 1").

**Comment by Greyhaven7** [comment]
I know it's been a while, but the plunker you linked is broken again. It's not displaying any labels, only a couple "/" separators with empty space between them.

**Comment by douglogsdon** [comment]
The ngSanitize module is required when binding to html within the template:
forked [plunker](http://plnkr.co/edit/2NUJQ5OVznuVZsNXeLP1?p=preview)
AngularJS [ngSanitize](https://docs.angularjs.org/api/ngSanitize)
AngularJS [ngBindHtml](https://docs.angularjs.org/api/ng/directive/ngBindHtml)
