### ISSUE TITLE
Label binding lost when using views object's '@' to target root <ui-view>

### ISSUE THREAD

**Issue by C-E-Rios** [ncuillery/angular-breadcrumb#89]
Firstly, thanks for a great module. 

I have a [plunker](http://plnkr.co/edit/PFuuTDUQBEsv5qk5u2KR?p=preview) which demonstrates my issue.

In my application I don't have a need for nested views, but I do use nested states. Rather than have a bunch of <ui-view> tags in every state's view, I use the view object with '@' to always target the root <ui-view>. The problem is that this approach looses the binding to a controller's value in the label declaration. Is there a workaround for this?

Thanks.

**Comment by ncuillery** [comment]
Hi, first of all, thanks for the plunker, very helpful for understanding the problem fastly.

As the [doc](https://github.com/ncuillery/angular-breadcrumb/wiki/API-Reference#state-options) says, the labels are always evaluated against the scope of the current state controller.

In case of nested views, the "detail" view is nested into the "element" view, so the scope the "detail" view gets the `idElement` property by inheritance.

When targeting the root view you break the hierarchy of scopes : "detail" scope is no more the child of "element" scope. So the `idElement` is unreachable in the "detail" state.

In that case, you have to make the properties / methods available in the child states. Here is some workarounds (from the dirtiest to the the smartest).
- Attach the properties / methods to the `$rootScope`
- Duplicate the properties / methods in child states' controllers.
- Use the [resolve](https://github.com/angular-ui/ui-router/wiki/Nested-States-and-Nested-Views#inherited-resolved-dependencies) property of state.

I hope I helped :smile:

**Comment by C-E-Rios** [comment]
You did thank you so much!
