### ISSUE TITLE
Release 0.4.0

### ISSUE THREAD

**Issue by ncuillery** [ncuillery/angular-breadcrumb#90]
- [x] Push to master
- [x] Push to gh-pages
- [x] Publish to npm
- [x] Update the wiki

**Comment by realityking** [comment]
I just tried to update, my the release is not yet tagged so it's not picked up by bower. Thank you.

**Comment by ncuillery** [comment]
I forgot the tag ! I should be ok now.

Good catch for the wrong version in CHANGELOG.md, I fixed it (I didn't amend the commit because it's already publish on npm).

**Comment by realityking** [comment]
Thank you :)
