### ISSUE TITLE
Can't deploy at http://www.webjars.org/bower

### ISSUE THREAD

**Issue by rema7** [ncuillery/angular-breadcrumb#92]
I've try to deploy your project to http://www.webjars.org/bower by pressing 'Add new Bower WebJar' button and got next message:

>Failed! No valid licenses found. No licenses were found. The acceptable licenses on BinTray are at: https://bintray.com/docs/api/#_footnote_1 License detection first uses the package metadata (e.g. package.json or bower.json) and falls back to looking for a LICENSE, LICENSE.txt, or LICENSE.md file in the master branch of the GitHub repo. Since these methods failed to detect a valid license you will need to work with the upstream project to add discoverable license metadata to a release or to the GitHub repo.

Can you create a copy of LICENSE-MIT to meet webjars.org requirements ?

TIA

**Comment by ncuillery** [comment]
Done !

Thanks for spreading my module :smile:

**Comment by rema7** [comment]
you're welcome ! :smile:
