### ISSUE TITLE
Dynamic amount of parents, subcategories

### ISSUE THREAD

**Issue by idiotstrike** [ncuillery/angular-breadcrumb#94]
I'm building simple community boards for my application. I'm encountering a problem right now, that is each forum category can have an unlimited amount of nested subcategories. My URLs would always look like this:

/forums/categories/1/category-slug, no matter which category they belong to, so that's not a problem.

I'd like to generate a dynamic breadcrumb tree based on the depth of a category, preferably in the state's controller. 

Is this achievable?

**Comment by ncuillery** [comment]
This module is strongly coupled to the ui-router configuration. So the situation is simple: if you have a ui-router's state for each categories and nested subcategories, `angular-breadcrumb` will help you.

The only way to have a dynamic breadcrumb with `angular-breadcrumb` is to have a dynamic tree of ui-router's states (it's tricky but possible I think).

Don't hesitate to ask Stackoverflow, it is a better place to ask technical questions and get help, [but you already know that right](http://stackoverflow.com/questions/30288859/angularjs-ui-router-two-identical-route-groups/30289753) ? :stuck_out_tongue:
