### ISSUE TITLE
Error using ncy-angular-breadcrumb

### ISSUE THREAD

**Issue by bfmehdi** [ncuillery/angular-breadcrumb#95]
If I use **'ncy-angular-breadcrumb'** to add the dependency I get an error 
Module **'ncy-angular-breadcrumb'** is not available! You either misspelled the module name or forgot to load it
If I use **ng-breadcrumbs** to add the dependencyI don't get any result when I use *div ncy-breadcrumb></div>*

**Comment by ncuillery** [comment]
Hi,

Your question is related to the correct declaration of modules in an angular application. Please read the official doc. Concerning the angular-breadcrumb module part, follow the Getting Started guide [here](https://github.com/ncuillery/angular-breadcrumb/wiki/Getting-started).

Note: don't confound this module with https://github.com/ianwalter/ng-breadcrumbs
