### ISSUE TITLE
Dynamically load Parent Labels

### ISSUE THREAD

**Issue by hwong668** [ncuillery/angular-breadcrumb#97]
This is probably related to #68, I've replied to that thread with a [plunkr] (http://plnkr.co/edit/Ij5qdqiKRQ5om8k1rmAX) but I guess since it has been marked answered previously, it is not alerting contributors. 

When I was debugging this locally, I notice ui-router has maintained the previous parent's label, nycbreadcrumb is just not grabbing it and I haven't dig into the breadcrumb code to understand why.

please help
Thanks

**Comment by ncuillery** [comment]
Hi, 

The "answered" only serve my purpose to don't let the issuers waiting a response for too long. It has no impact on contributors notifications.

I should have removed this label when you commented #68 :smile:

**Comment by ncuillery** [comment]
I report your message in #68. I close this one.
